site_name: 一个测试项目
site_url: https://github.com/Tao11273/MM_test_202508.git
theme:
  name: material
  logo: assets/flowers.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: blue
      accent: deep orange


    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: green
      accent: deep purple


extra_css:
  - css/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - i18n:
      languages:
        - locale: zh
          name: 简体中文
          default: true
          build: true
        - locale: en
          name: English
          default: false
          build: true
  - search:
      lang: 
          - zh
          - en
